Feature: Employee
	IN ORDER TO ENSURE THAT THE EMPLOYEE MODEL IS FUNCTIONAL
	AS A LOGGED-IN USER
	I SHOULD BE ABLE TO PERFORM REST OPERATIONS ON EMPLOYEE ENTITIES

@smoke @employee
Scenario: Create Employee With Full Details
	Given I HAVE NAVIGATED TO THE APPLICATION
	And I CONFIRM THE APPLICATION IS RUNNING
	And I CLICK THE LOGIN LINK
	When I ENTER MY USERNAME AND PASSWORD
	| USERNAME | PASSWORD |
	| admin    | password |
	And I CLICK THE LOGIN BUTTON
	And I FOLLOW THE EMPLOYEE LIST LINK
	And I CLICK THE CREATE NEW [EMPLOYEE] BUTTON
	And I ENTER THE DETAILS OF THE EMPLOYEE
	| NAME           | SALARY | WORK HOURS | GRADE | EMAIL          |
	| Automated User | 4000   | 30         | 1     | auto@user.spec |
	And I CLICK THE CREATE [EMPLOYEE] BUTTON
	Then THE NEWLY CREATED EMPLOYEE SHOULD HAVE SUCCESSFULLY SAVED