Feature: Login
	IN ORDER TO ACCESS MY ACCOUNT
	AS A USER OF THE WEBSITE
	I SHOULD BE ABLE TO LOG IN WITH MY USERNAME AND PASSWORD

Background:
	#Given I DELETE EMPLOYEE "Automated Employee" PRIOR TO RUNNING TEST

@smoke @authentication
Scenario: Assert Login With Valid Credentials
	Given I HAVE NAVIGATED TO THE APPLICATION
	And I CONFIRM THE APPLICATION IS RUNNING
	And I CLICK THE LOGIN LINK
	When I ENTER MY USERNAME AND PASSWORD
	| USERNAME | PASSWORD |
	| admin    | password |
	And I CLICK THE LOGIN BUTTON
	Then I SHOULD BE AUTHENTICATED AND SEE A GREETING MESSAGE