using System.Collections.Generic;
using HtmlAgilityPack;
using OpenQA.Selenium;

namespace FrameworkCore.Extensions
{
    public static partial class WebElementExtensions
    {
        public static HtmlNode GetHTTPTableNode(this IWebElement element)
        {
            // TODO: Implement GetHTTPTableNode via HtmlAgilityPack

            return null;
        }

        public static IList<HtmlNode> GetHTTPTableNodes()
        {
            // TODO: Implement GetHTTPTableNodes via HtmlAgilityPack

            return null;
        }

        /* * * * *
         * https://dotnetfiddle.net/UXCBxf
         * https://stackoverflow.com/questions/13005098/parsing-html-table-in-c-sharp
         * https://html-agility-pack.net/documentation
         */
    }
}
